<?php

namespace Navalex\ConfigBundle\Repository;

/**
 * FieldsetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldsetRepository extends \Doctrine\ORM\EntityRepository
{
}
